"""empty message

Revision ID: 142d587e5f2d
Revises: b313661d57f6
Create Date: 2023-06-23 22:02:58.899442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '142d587e5f2d'
down_revision = 'b313661d57f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('distress_log', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('time',
               existing_type=sa.TIME(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('distress_level',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('duration',
               existing_type=sa.FLOAT(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('phone_number',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('distress_log', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('duration',
               existing_type=sa.REAL(),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('distress_level',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('time',
               existing_type=sa.Text(),
               type_=sa.TIME(),
               existing_nullable=True)
        batch_op.alter_column('date',
               existing_type=sa.Text(),
               type_=sa.DATE(),
               existing_nullable=True)

    # ### end Alembic commands ###
