"""Add network_ssid column to distress_log table

Revision ID: e4f7f30431dc
Revises: 142d587e5f2d
Create Date: 2023-06-25 13:25:58.062344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4f7f30431dc'
down_revision = '142d587e5f2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('distress_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('network_ssid', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('distress_log', schema=None) as batch_op:
        batch_op.drop_column('network_ssid')

    # ### end Alembic commands ###
